### ISSUE TITLE
Network connectivity issues

### ISSUE THREAD

**Issue by mcandre** [1ambda/docker-kafka-connect#7]
1ambda/docker-kafka-connect doesn't work on my machine (Mac OS with Docker Toolbox). However, I am having better luck with Debezium's Kafka Connect and ZooKeeper Docker images, and Confluent's official Kafka image.

https://github.com/mcandre/hello-kafka-connect/blob/master/docker-compose-docker-machine.yml.sample

https://github.com/mcandre/hello-kafka-connect#example

I'm not sure why 1ambda/docker-kafka-connect doesn't work on my host. Was the 1ambda image tested on a non-Linux host?

**Comment by 1ambda** [comment]
Hi @mcandre 

I'v test on OSX 10.11

``` shell
$  dk -v
Docker version 1.12.0-rc4, build e4a0dbc, experimental

$  dkm -v
docker-machine version 0.8.0-rc2, build 4ca1b85

$ dkc -v
docker-compose version 1.8.0-rc2, build c72c966
```

**Comment by mcandre** [comment]
Update: Auto-topic-creation still fails, and connect continues to display offset commit errors. However, thanks to your 1ambda/kafka-connect image, I'm able to get a basically working Kafka Connect stack in docker-compose!!!

https://github.com/mcandre/hello-kafka-connect
