### ISSUE TITLE
Publish version tag for DockerHub images

### ISSUE THREAD

**Issue by mcandre** [1ambda/docker-kafka-connect#9]
Please publish a version tag for 1ambda/kafka-connect on DockerHub, to protect users against changes.

Example:

```
$ docker tag 1ambda/kafka-connect 1ambda/kafka-connect:0.10.0.0
$ docker push 1ambda/kafka-connect:0.10.0.0
```

**Comment by 1ambda** [comment]
@mcandre

What about `1ambda/kafka-connect:0.10.0.1-v1`? It's in case published images is wrong

**Comment by mcandre** [comment]
that works, too!

**Comment by 1ambda** [comment]
It's somewhat late. I'v pushed `1ambda/kafka-connect:0.10.0.0` without the `v1` postfix. See [tag](https://hub.docker.com/r/1ambda/kafka-connect/tags/)

:)
